### ISSUE TITLE
16-bit eagle board has 12-bit adc 

### ISSUE THREAD

**Issue by theotherjenkutler** [adafruit/ADS1X15-Breakout-Board-PCBs#4]
Am I missing something here?
![Screen Shot 2020-10-25 at 1 20 42 PM](https://user-images.githubusercontent.com/7742177/97114127-026d0680-16c5-11eb-8712-5a013333ae3d.png)

**Comment by theotherjenkutler** [comment]
![Screen Shot 2020-10-25 at 1 22 34 PM](https://user-images.githubusercontent.com/7742177/97114157-2deff100-16c5-11eb-8fd3-2d6307e1065b.png)

**Comment by ladyada** [comment]
its the same pinout and size, we recycle the part.
