### ISSUE TITLE
ADS1X15-Breakout-Board-PCBs missing connection in PCB layout

### ISSUE THREAD

**Issue by ScotsDon** [adafruit/ADS1X15-Breakout-Board-PCBs#5]
I downloaded the Eagle files using the Zip file download and imported them into KiCad.  On the KiCad PCB Layout Editor, there is marked a "rats nest" connection with no actual track.  The actual PCB I have does have this connection, so it's a drawing issue.  The missing track is between the GND Via adjacent to capacitor C1 (which is across VDD and GND very near the ADS1115 chip) and GND.  The Via then connects to the chip GND.   I assume this is known about, but I thought it should be reported so the drawing gets updated.

**Comment by ladyada** [comment]
hi the original eaglecad does not have any unrouted lines

**Comment by ScotsDon** [comment]
Thanks.  It's a KiCad issue then.
