### ISSUE TITLE
Won't open in Eagle 9.6.2 or Fusion 360 "not an Eagle File"

### ISSUE THREAD

**Issue by Bretthansenpc** [adafruit/ADS1X15-Breakout-Board-PCBs#7]
When I try to open this on either platform it shows an error saying it's not an eagle file with the error:

"line 8, column 88: This is not an EAGLE file."

I have no idea if I'm doing something wrong any help would be great!

**Comment by ladyada** [comment]
https://learn.adafruit.com/accessing-and-using-adafruit-pcb-design-files
